# Generated by Django 4.2 on 2023-12-07 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bench',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_latitude', models.FloatField(verbose_name='Широта')),
                ('location_longitude', models.FloatField(verbose_name='Долгота')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='user_avatars/')),
                ('rating', models.IntegerField(default=0)),
                ('has_backrest', models.BooleanField(blank=True, default=None, null=True)),
                ('has_bin', models.BooleanField(blank=True, default=None, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('deskription', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Скаймейка',
                'verbose_name_plural': 'Скаймейки',
            },
        ),
        migrations.CreateModel(
            name='BenchDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Район скамейки')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='bench_district/')),
            ],
            options={
                'verbose_name': 'Район скамейки',
                'verbose_name_plural': 'Район скамеек',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BenchEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Окружение скамейки')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='bench_environment/')),
            ],
            options={
                'verbose_name': 'Окружение скамейки',
                'verbose_name_plural': 'Окружение скамеек',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BenchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Тип скамейки')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='bench_type/')),
            ],
            options={
                'verbose_name': 'Тип скамейки',
                'verbose_name_plural': 'Тип скамеек',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BenchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bench/<bound method Field.__str__ of <django.db.models.fields.related.ForeignKey>>', verbose_name='Дополнительное фото')),
                ('bench', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='benches.bench')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='bench',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benches.benchdistrict'),
        ),
        migrations.AddField(
            model_name='bench',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benches.benchenvironment'),
        ),
        migrations.AddField(
            model_name='bench',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benches.benchtype'),
        ),
    ]
